
const exceptionHandler = process.on('uncaughtException', (reason, promise) => {
    const message = `Promise rejeitada e nÃ£o tratada (${promise}). Motivo: ${reason}`;
    console.log(message);
});